### ISSUE TITLE
Popover z-index is astronomical and global

### ISSUE THREAD

**Issue by smargovsky** [UW-Madison-DoIT/uw-frame#26]
Currently, the popover z-index is set VERY high and out of the specific order implemented by bootstrap.

in webapp/css/buckyless/sidebar.less
```css
    .popover {
       z-index:9999;
    }
```
This is causing issues in our Advising Gateway app.  I'd like to know if I can pull request this out or specify it more specifically to the needed use-case ( in the sidebar? ).  Please and thank you.
